version: "3.8"

services:
  # Nginx CDN service
  nginx-cdn:
    image: nginx:latest
    container_name: nginx-cdn
    ports:
      - "3302:80"  #CDN port
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/cache/nginx
    depends_on:
      - proxy-manager
    networks:
      - nginx-net

  # Nginx Proxy Manager service
  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-ui
    restart: unless-stopped
    ports:
      - "3303:81"   # UI
      - "8081:80"   # HTTP entry（Reverse Proxy）
      - "8443:443"  # HTTPS entry
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: 'pgdb'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'npmpass'
      DB_POSTGRES_NAME: 'npm'
    # Uncomment this if IPv6 is not enabled on your host
    # DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-net
  # PostgreSQL database service for Nginx Proxy Manager
  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: npm
      POSTGRES_PASSWORD: npmpass
      POSTGRES_DB: npm
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - nginx-net
# Set the Docker network
networks:
  nginx-net:
    driver: bridge